{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubegpt.fullname" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubegpt.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: kubegpt
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "kubegpt.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}