{{- if .Values.aiToken }}
apiVersion: v1
data:
  secretKey: {{ .Values.aiToken | b64enc | quote }}
kind: Secret
metadata:
  labels:
  {{- include "kubegpt.labels" . | nindent 4 }}
  name: {{ include "kubegpt.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}