{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubegpt
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubegpt.labels" . | nindent 4 }}

{{- end }}
