apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubegpt.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubegpt.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - *
    resources:
      - *
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch